# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edf965adb19a93b40112f44622de159786fef77e95cc96e8b68269d8644fcf0940bf3648bd64fb2c8a343b6f7c4e47023ff2078d61b6d65d323bd5bafd8c5c85

test:
  secret_key_base: e931e26aceadf9fef32db4451b1ee07457b9327a8e21282c270cbb595d40f977c82938382f2fbd57f6cee43d596f6257ec9c3e843c9643b267f364a85fa85923

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
